export const CONFIG = {
  // Track
  LANE_WIDTH: 2.8,
  LANE_POSITIONS: [-2.8, 0, 2.8],
  TRACK_SEGMENT_LENGTH: 40,
  TRACK_VISIBLE_SEGMENTS: 6,
  TRACK_WIDTH: 12,

  // Player
  PLAYER_START_LANE: 1,
  PLAYER_Y: 0.5,
  PLAYER_SWITCH_SPEED: 12,
  JUMP_FORCE: 0.28,
  GRAVITY: 0.012,
  PLAYER_SIZE: 0.7,

  // Speed & Difficulty
  BASE_SPEED: 0.28,
  MAX_SPEED: 0.85,
  SPEED_INCREMENT: 0.01,
  STREAK_SPEED_BONUS: 10,
  SPAWN_DISTANCE: 55,
  DESPAWN_DISTANCE: 15,

  // Spawning
  NPC_SPAWN_INTERVAL: 70,
  BARRIER_SPAWN_INTERVAL: 110,
  MIN_SPAWN_GAP: 30,

  // Crowd
  MAX_CROWD: 80,
  CROWD_SPACING: 1.4,
  CROWD_LATERAL_SPREAD: 1.6,
  CROWD_Y_VARIATION: 0.15,
  CROWD_Z_OFFSET: 2.2,
  CROWD_ROW_SIZE: 3,

  // NPC Collision
  NPC_COLLISION_Z_FRONT: 1.5,
  NPC_COLLISION_Z_BACK: -0.5,
  NPC_COLLISION_VERTICAL_TOLERANCE: 1.2,

  // Barrier Collision
  BARRIER_COLLISION_Z_FRONT: 1.2,
  BARRIER_COLLISION_Z_BACK: -0.8,
  BARRIER_COLLISION_HEIGHT: 1.4,
  BARRIER_CLEAR_HEIGHT: 1.8,

  // Mismatch
  MISMATCH_CROWD_LOSS: 2,
  MISMATCH_SPEED_FRACTION: 0.015,
  MISMATCH_SPEED_RECOVERY_FRAMES: 90,

  // Barrier crash
  BARRIER_CROWD_LOSS_PERCENT: 0.4,
  BARRIER_SPEED_PENALTY: 0.03,

  // Speed formula
  // speed = BASE_SPEED + floor(streak / STREAK_SPEED_BONUS) * SPEED_INCREMENT

  // Visual
  BG_COLOR: 0x1a0a2e,
  TRACK_COLOR: 0x2a1a4e,
  LANE_LINE_COLOR: 0x4a3a7e,
  AMBIENT_LIGHT: 0x6644aa,
  DIRECTIONAL_LIGHT: 0xffeedd,

  // Shapes
  SHAPES: ['circle', 'triangle', 'square'],
  COLORS: {
    circle: 0x4a9eff,
    triangle: 0xff4a6a,
    square: 0x4aff8a
  },
  COLOR_NAMES: {
    circle: 'blue',
    triangle: 'red',
    square: 'green'
  },

  // Perfect Match / Perfect Catch
  PERFECT_MATCH_WINDOW: 0.35,

  // Multi-target & Risk/Safe
  MULTI_TARGET_PROBABILITY: 0.3,
  MULTI_TARGET_MAX_COUNT: 3,
  RISK_TARGET_PROBABILITY: 0.4,
  RISK_CROWD_REWARD: 3,
  SAFE_CROWD_REWARD: 1,
  RISK_SPAWN_DELAY: 8,
  EARLY_GAME_DURATION: 30000,

  // NPC Visual Fix
  NPC_WALL_CLEARANCE: 0.15,
  NPC_VISUAL_SCALE: 0.85,

  // Track boundaries (derived)
  TRACK_HALF_WIDTH: 6,
  TRACK_INNER_BOUNDARY: 6,

  // Moving NPC
  MOVING_NPC_PROBABILITY: 0.075,
  MOVING_NPC_EARLY_GAME_DURATION: 30000,
  MOVING_NPC_MOVE_START_DISTANCE: 25,
  MOVING_NPC_MOVE_DURATION: 25,

  // NPC-Obstacle Visual Separation
  NPC_OBSTACLE_VISUAL_GAP: 18,
  NPC_OBSTACLE_SAME_LANE_GAP: 24,
  NPC_OBSTACLE_MULTI_TARGET_GAP: 16,

  // Near Miss
  NEAR_MISS_DISTANCE: 3.5,
  NEAR_MISS_COOLDOWN_FRAMES: 45,

  // Flow Aura (10 streak)
  FLOW_STREAK_THRESHOLD: 10,
  FLOW_DURATION: 5,
  FLOW_AURA_COLOR: 0xffd700,
  FLOW_PARTICLE_COUNT: 12,
  FLOW_RING_COUNT: 3,

  // Perfect Combo
  PERFECT_COMBO_THRESHOLD_3: 3,
  PERFECT_COMBO_THRESHOLD_5: 5,
  PERFECT_COMBO_RESET_ON_NORMAL: true,

  // Near Miss Chain
  NEAR_MISS_CHAIN_THRESHOLD_2: 2,
  NEAR_MISS_CHAIN_THRESHOLD_3: 3,
  NEAR_MISS_CHAIN_TIMEOUT: 120,

  // Crowd Formation Milestones
  CROWD_FORMATION_MILESTONES: [10, 25, 50],

  // Rival Crowd
  RIVAL_SPAWN_MIN_STREAK: 15,
  RIVAL_SPAWN_PROBABILITY: 0.02,
  RIVAL_CROWD_SIZE: 8,
  RIVAL_SPAWN_COOLDOWN: 300,

  // Effects
  MAX_PARTICLES: 80,
  PARTICLE_LIFETIME: 600,
  TRAIL_LENGTH: 8,

  // Debug
  DEBUG_COLLISION: false,
  DEBUG_SPAWN: false
};
